name: Dev Container Build and Push Image

env:
  ACTIONS_RUNNER_DEBUG: true

on: [push]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Capture lowercase github.repository
      run: |
        echo "IMAGE_NAME=${GITHUB_REPOSITORY@L}" >> ${GITHUB_ENV}
    - name: Pre-build dev container image
      uses: devcontainers/ci@v0.2
      with:
        subFolder: .github
        imageName: ghcr.io/${{ env.IMAGE_NAME }}
        cacheFrom: ghcr.io/${{ env.IMAGE_NAME }}
        push: always
